# docker-compose.yml
version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  importer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
    command: poetry run typer importer.run fetch
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
    command: typer data_pipeline.worker export